### ISSUE TITLE
Text box for choice of Language instantly disappears

### ISSUE THREAD

**Issue by chankai420** [chaoskagami/MaihanaTL#1]
When running build.sh, the text box for the choice of language appears. However, the text box instantly disappears before the language can be chosen. Is it the way I run it or is it just broken?

**Comment by chaoskagami** [comment]
I should really mark this as "unsupported" and archive the repo. There's an official release on the Nintendo [Switch](https://www.nintendo.com/games/detail/azure-reflections-switch/) and [PS4](https://store.playstation.com/en-us/product/UP2815-CUSA11431_00-MAIHANA000000000) - you should support that instead of my incomplete and broken half-translation that predates that. It's very likely not updated to handle whatever the latest version is, so you're on your own here.
